/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import Beans.Usuario;
import DAOS.UsuarioDAO;

/**
 *
 * @author Felipe
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     *
     */
    public TelaLogin() {
        initComponents();
        setLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        informjLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        enterjButton1 = new javax.swing.JButton();
        canceljButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informjLabel1.setToolTipText("");
        jPanel1.add(informjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 92, 229, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mario Souto\\Downloads\\bunch-of-keys-1--v1.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(51, 102, 255));
        loginLabel.setText("LOGIN");
        jPanel1.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 32));

        senhaLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(51, 102, 255));
        senhaLabel.setText("SENHA");
        jPanel1.add(senhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 32));

        login.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        login.setSelectionColor(new java.awt.Color(255, 0, 0));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 230, 32));

        senha.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 230, 31));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("IDENTIFICAÇÃO DO USUÁRIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        enterjButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enterjButton1.setForeground(new java.awt.Color(51, 102, 255));
        enterjButton1.setText("ACESSAR");
        enterjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterjButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(enterjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 90, 40));

        canceljButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        canceljButton2.setForeground(new java.awt.Color(51, 102, 255));
        canceljButton2.setText("SAIR");
        canceljButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(canceljButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 90, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 90, 40));

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("SISTEMA GESTÃO DE AUTO ESCOLAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed

    }//GEN-LAST:event_senhaActionPerformed

    private void enterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterjButton1ActionPerformed
        Usuario logado = this.logar();
        if (logado == null) {
            JOptionPane.showMessageDialog(rootPane, "Dados incorretos!\nPor favor verifique o login ou a senha e tente novamente.");
        } else {
            telaPrincipal tela = new telaPrincipal();
            tela.setExtendedState(tela.MAXIMIZED_BOTH);
            tela.setVisible(true);
            setVisible(false);
            dispose();

        }
        login.setText("");
        senha.setText("");    
    }//GEN-LAST:event_enterjButton1ActionPerformed

    private void canceljButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButton2ActionPerformed
        dispose();        
    }//GEN-LAST:event_canceljButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login.setText("");
        senha.setText("");         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private Usuario logar() {

        UsuarioDAO dao = new UsuarioDAO();
        String loginCampo = login.getText();
        String senhaCampo = new String(senha.getPassword());
        String senhaCriptografada = this.criptografa(senhaCampo);
        Usuario usuario = new Usuario();
        usuario.setLogin(loginCampo);
        usuario.setSenha(senhaCriptografada);
        return dao.localizar(usuario);
    }

    private String criptografa(String original) {
        String senha = null;
        try {
            MessageDigest algorithm = MessageDigest.getInstance("SHA-256");
            byte messageDigest[] = algorithm.digest(original.getBytes("UTF-8"));

            StringBuilder hexString = new StringBuilder();
            for (byte b : messageDigest) {
                hexString.append(String.format("%02X", 0xFF & b));
            }
            senha = hexString.toString();
        } catch (NoSuchAlgorithmException | UnsupportedEncodingException e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
        return senha;
    }

    public void setLayout() {

        setVisible(true);
        dispose();
        setVisible(true);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                TelaLogin tl = new TelaLogin();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceljButton2;
    private javax.swing.JButton enterjButton1;
    private javax.swing.JLabel informjLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField senha;
    private javax.swing.JLabel senhaLabel;
    // End of variables declaration//GEN-END:variables
}
