/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAOS.TurmaDAO;
import Beans.Turma;
import DAOS.AlunoDAO;
import Beans.Aluno;
import DAOS.AlunoTurmaDAO;
import Beans.AlunoTurma;
import DAOS.InstrutorDAO;
import DAOS.salaDAO;
import Beans.Sala;
import Beans.Instrutor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario Souto
 */
public class telaTurmas extends javax.swing.JFrame {

    /**
     * Creates new form telaTurmas
     */
    public telaTurmas() {
        initComponents();
        TurmaDAO turmaDAO = new TurmaDAO();
        InstrutorDAO instrutoDAO = new InstrutorDAO();

        atualizaTabelaTurmas();
        atualizaTabelaAlunos();
        atualizaTabelaAlunosTurma();
        comboBOX();
        comboBOX2();
        comboBOX3();
        comboBOX4();
    
    }

    public void atualizaTabelaTurmas() {

        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaTurmas.getModel();
        modeloTabela.setNumRows(0);

        TurmaDAO dao = new TurmaDAO();

        for (Turma t : dao.lista()) {

            modeloTabela.addRow(new Object[]{
                t.getIdturma(),
                t.getNometurma(),
                t.getInstrutor(),
                t.getSalaafk()});
        }

    }

    public void atualizaTabelaAlunos() {

        DefaultTableModel modeloTabela2 = (DefaultTableModel) tabelaAlunos.getModel();
        modeloTabela2.setNumRows(0);

        AlunoDAO dao = new AlunoDAO();

        for (Aluno a : dao.lista()) {

            modeloTabela2.addRow(new Object[]{
                a.getIdaluno(),
                a.getNome(),
                a.getCategoria(),});
        }

    }

    public void atualizaTabelaAlunosTurma() {

        DefaultTableModel modeloTabela3 = (DefaultTableModel) tabelaAlunosTurma.getModel();
        modeloTabela3.setNumRows(0);

        AlunoTurmaDAO dao = new AlunoTurmaDAO();
        AlunoDAO dao2 = new AlunoDAO();

        for (AlunoTurma a : dao.lista()) {

            if (a.getIdTurma().equals(a)) {
                modeloTabela3.addRow(new Object[]{
                    a.getId(),
                    a.getIdTurma().getNometurma(),
                    a.getIdAluno().getNome(),
                    a.getIdTurma().getInstrutor(),
                    a.getIdTurma().getSalaafk()});
            }

        }

    }

    private void jTableKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

        if (tabelaTurmas.getSelectedRow() != -1) {
            turmaI.setText(tabelaTurmas.getValueAt(tabelaTurmas.getSelectedRow(), 2).toString());
            boxInstrutor.setSelectedItem(tabelaTurmas.getValueAt(tabelaTurmas.getSelectedRow(), 3).toString());

        }

    }

    public void comboBOX() {

        InstrutorDAO instrutorDAO = new InstrutorDAO();

        this.boxInstrutor.removeAllItems();

        for (Instrutor i : instrutorDAO.lista()) {

            this.boxInstrutor.addItem(i);

        }

    }

    public void comboBOX2() {

        salaDAO dao = new salaDAO();

        this.boxSala.removeAllItems();

        for (Sala s : dao.lista()) {

            this.boxSala.addItem(s);

        }

    }

    public void comboBOX3() {

        InstrutorDAO instrutorDAO = new InstrutorDAO();

        this.boxInstrutor2.removeAllItems();

        for (Instrutor i : instrutorDAO.lista()) {

            this.boxInstrutor2.addItem(i);

        }

    }

    public void comboBOX4() {

        salaDAO dao = new salaDAO();

        this.boxSala2.removeAllItems();

        for (Sala s : dao.lista()) {

            this.boxSala2.addItem(s);

        }

    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTurmas = new javax.swing.JTable();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        turmaI = new javax.swing.JTextField();
        inserir = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        boxInstrutor = new javax.swing.JComboBox<>();
        boxSala = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        turmaE = new javax.swing.JTextField();
        editar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        boxSala2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        boxInstrutor2 = new javax.swing.JComboBox<>();
        limpar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAlunosTurma = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        inserirJogadores = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        excluirJogadores = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        excluirJogadores1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Instrutor", "Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTurmasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaTurmas);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir"));

        jLabel2.setText("TURMA");

        jLabel3.setText("INSTRUTOR ");

        jLabel4.setText("DISCIPLINA");

        inserir.setText("INSERIR");
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });

        limpar.setText("LIMPAR");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(turmaI)
                                    .addComponent(boxInstrutor, 0, 159, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(boxSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(limpar)
                        .addGap(18, 18, 18)
                        .addComponent(inserir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(turmaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(boxInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(boxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserir)
                    .addComponent(limpar))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar"));

        jLabel5.setText("TURMA");

        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        jLabel13.setText("DISCIPLINA");

        jLabel8.setText("INSTRUTOR ");

        limpar1.setText("LIMPAR");
        limpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(limpar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editar))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(boxInstrutor2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(turmaE, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(boxSala2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turmaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(boxInstrutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(boxSala2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(limpar1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel9.setText("(Para inserir alunos na Turma selecione a turma e insira o aluno.)");

        jLabel10.setText("(Alunos na Turma)");

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaAlunos);

        tabelaAlunosTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Turma", "Aluno", "Instrutor", "Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaAlunosTurma);

        jLabel11.setText("(Inserir alunos na Turma)");

        inserirJogadores.setText("INSERIR");
        inserirJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirJogadoresActionPerformed(evt);
            }
        });

        jLabel12.setText("(Excluir alunos da Turma)");

        excluirJogadores.setText("EXCLUIR");
        excluirJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirJogadoresActionPerformed(evt);
            }
        });

        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel14.setText("(Para remover selecione a turma na tabela acima e clique no botao excluir)");

        excluirJogadores1.setText("EXCLUIR");
        excluirJogadores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirJogadores1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(inserirJogadores))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(excluirJogadores))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(excluirJogadores1)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirJogadores1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inserirJogadores)
                            .addComponent(excluirJogadores)
                            .addComponent(jLabel11))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTurmasMouseClicked

        int selecionado = tabelaTurmas.getSelectedRow();
        String turma = (String) tabelaTurmas.getValueAt(selecionado, 1);
        Instrutor instrutor = (Instrutor) tabelaTurmas.getValueAt(selecionado, 2);
        Sala sala = (Sala) tabelaTurmas.getValueAt(selecionado, 3);

        turmaE.setText(turma);
        boxInstrutor2.getModel().setSelectedItem(instrutor);
        boxSala2.getModel().setSelectedItem(sala);
    }//GEN-LAST:event_tabelaTurmasMouseClicked

    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed

        Turma t = new Turma();
        TurmaDAO turmaDAO = new TurmaDAO();
        Instrutor I = new Instrutor();
        Sala s = new Sala();

        t.setNometurma(turmaI.getText());
        Instrutor instrutorSelecionado = (Instrutor) this.boxInstrutor.getSelectedItem();
        t.setInstrutor(instrutorSelecionado);

        Sala salaSelecionada = (Sala) this.boxSala.getSelectedItem();
        t.setSalaafk(salaSelecionada);

        turmaDAO.adiciona(t);
        atualizaTabelaTurmas();
        turmaI.setText("");
        boxInstrutor.setSelectedIndex(0);
        boxSala.setSelectedIndex(0);


    }//GEN-LAST:event_inserirActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        turmaI.setText("");
        boxInstrutor.setSelectedIndex(0);
        boxSala.setSelectedIndex(0);

    }//GEN-LAST:event_limparActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

        if (tabelaTurmas.getSelectedRow() != -1) {
            Turma t = new Turma();
            TurmaDAO dao = new TurmaDAO();

            t.setNometurma(turmaE.getText());
            Instrutor instrutorSelecionado = (Instrutor) this.boxInstrutor2.getSelectedItem();
            t.setInstrutor(instrutorSelecionado);

            Sala salaSelecionada = (Sala) this.boxSala2.getSelectedItem();
            t.setSalaafk(salaSelecionada);
            t.setIdturma((int) tabelaTurmas.getValueAt(tabelaTurmas.getSelectedRow(), 0));
            dao.altera(t);
            atualizaTabelaTurmas();
            atualizaTabelaAlunosTurma();

            turmaE.setText("");
            boxInstrutor2.setSelectedIndex(0);
            boxSala2.setSelectedIndex(0);

            JOptionPane.showMessageDialog(null, "Alterado com sucesso!", "Adicionado", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_editarActionPerformed

    private void inserirJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirJogadoresActionPerformed

        AlunoTurmaDAO alunoturmaDAO = new AlunoTurmaDAO();

        int linhaT = tabelaTurmas.getSelectedRow();
        TurmaDAO dao = new TurmaDAO();
        Turma t = dao.lista().get(linhaT);

        int linhaJ = tabelaAlunos.getSelectedRow();
        AlunoDAO dao2 = new AlunoDAO();
        Aluno a = dao2.lista().get(linhaJ);

        boolean at = alunoturmaDAO.AlunoJaCadastrado(t, a);

        if (at) {
            JOptionPane.showMessageDialog(null, "Aluno já cadastrado na turma.", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            alunoturmaDAO.adiciona(t, a);
            JOptionPane.showMessageDialog(null, "Adicionado com sucesso!", "Adicionado", JOptionPane.INFORMATION_MESSAGE);
            atualizaTabelaAlunosTurma();

        }
    }//GEN-LAST:event_inserirJogadoresActionPerformed

    private void excluirJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJogadoresActionPerformed

        AlunoTurma a = new AlunoTurma();
        AlunoTurmaDAO dao = new AlunoTurmaDAO();

        if (tabelaAlunosTurma.getSelectedRow() != -1) {
            a.setId((int) tabelaAlunosTurma.getValueAt(tabelaAlunosTurma.getSelectedRow(), 0));
            dao.exclui(a);
            JOptionPane.showMessageDialog(null, "Excluido com sucesso!", "Excluido", JOptionPane.INFORMATION_MESSAGE);
            atualizaTabelaAlunosTurma();

        }

    }//GEN-LAST:event_excluirJogadoresActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed

        telaPrincipal tela = new telaPrincipal();
        tela.setExtendedState(tela.MAXIMIZED_BOTH);
        tela.setVisible(true);
        setVisible(false);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void excluirJogadores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJogadores1ActionPerformed

        Turma t = new Turma();
        TurmaDAO dao = new TurmaDAO();

        if (tabelaTurmas.getSelectedRow() != -1) {
            t.setIdturma((int) tabelaTurmas.getValueAt(tabelaTurmas.getSelectedRow(), 0));
            dao.exclui(t);
            JOptionPane.showMessageDialog(null, "Excluido com sucesso!", "Excluido", JOptionPane.INFORMATION_MESSAGE);
            atualizaTabelaTurmas();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_excluirJogadores1ActionPerformed

    private void limpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar1ActionPerformed
        // TODO add your handling code here:
        turmaE.setText("");
        boxInstrutor2.setSelectedIndex(0);
        boxSala2.setSelectedIndex(0);


    }//GEN-LAST:event_limpar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                telaTurmas tu = new telaTurmas();
                tu.setVisible(true);
                tu.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> boxInstrutor;
    private javax.swing.JComboBox<Object> boxInstrutor2;
    private javax.swing.JComboBox<Object> boxSala;
    private javax.swing.JComboBox<Object> boxSala2;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluirJogadores;
    private javax.swing.JButton excluirJogadores1;
    private javax.swing.JButton inserir;
    private javax.swing.JButton inserirJogadores;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpar;
    private javax.swing.JButton limpar1;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTable tabelaAlunosTurma;
    private javax.swing.JTable tabelaTurmas;
    private javax.swing.JTextField turmaE;
    private javax.swing.JTextField turmaI;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
